import js from '@eslint/js';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'PharmaDash-v3-medical-ready.html',
      'pharmdash v3 medical.html',
    ],
  },
  js.configs.recommended,
  {
    files: ['src/app.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'script',
      globals: {
        console: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        indexedDB: 'readonly',
        crypto: 'readonly',
        Chart: 'readonly',
        XLSX: 'readonly',
        pdfjsLib: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        matchMedia: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
      },
    },
    rules: {
      'no-undef': 'off',
      'no-unused-vars': 'off',
      'no-empty': 'off',
    },
  },
  {
    files: ['src/core/**/*.mjs', 'scripts/**/*.mjs', 'tests/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        Buffer: 'readonly',
        console: 'readonly',
        process: 'readonly',
        URL: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
    },
  },
  {
    files: ['tests/e2e/**/*.mjs'],
    languageOptions: {
      globals: {
        indexedDB: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        setBranchData: 'readonly',
        STATE: 'readonly',
        renderAll: 'readonly',
        _idbPut: 'readonly',
        _idbGet: 'readonly',
        _IDB_KEY: 'readonly',
        _buildSnapshot: 'readonly',
        PharmaCore: 'readonly',
        aggregate: 'readonly',
        rebuildBranchFromPeriods: 'readonly',
        doLogout: 'readonly',
        printVisitCard: 'readonly',
        saveData: 'readonly',
        flushSaveData: 'readonly',
        aggregateAsync: 'writable',
        loadSavedData: 'readonly',
        lockInMemoryData: 'readonly',
        dtOpenUpload: 'readonly',
        dtHandleFile: 'readonly',
        DT: 'readonly',
        charts: 'readonly',
        window: 'readonly',
        parseCSV: 'writable',
        parseExcel: 'readonly',
        handleFile: 'readonly',
        closeModal: 'readonly',
        renderNearExpiry: 'readonly',
        XLSX: 'readonly',
        File: 'readonly',
        setTimeout: 'readonly',
      },
    },
  },
];
